apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
  - name: cont1
    image: nginx:alpine
--- # Con esta linea se puede tener más de un componente en un mismo archivo
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
spec:
  containers:
  - name: cont1
    image: nginx:alpine