apiVersion: v1
kind: Pod
metadata:
  name: labels-front
  labels:
    app: front
    env: dev
spec:
  containers:
  - name: cont1
    image: nginx:alpine
--- # Con esta linea se puede tener más de un componente en un mismo archivo
apiVersion: v1
kind: Pod
metadata:
  name: labels-backend
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: cont1
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: labels-backend-2
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: cont1
    image: nginx:alpine